#!/usr/bin/env bash
set -euo pipefail

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEST_DIR="${1:-}"

if [[ -z "${DEST_DIR}" ]]; then
  echo "Usage: $0 /path/to/new/repo-dir" >&2
  exit 1
fi

if [[ -e "${DEST_DIR}" ]]; then
  echo "Destination already exists: ${DEST_DIR}" >&2
  exit 1
fi

mkdir -p "${DEST_DIR}"

copy_with_rsync() {
  rsync -a \
    --exclude='.git/' \
    --exclude='.gitmodules' \
    --exclude='.cache/' \
    --exclude='__pycache__/' \
    --exclude='.pytest_cache/' \
    --exclude='.mypy_cache/' \
    --exclude='artifacts/' \
    --exclude='cache/' \
    --exclude='logs/' \
    --exclude='miniforge/' \
    --exclude='outputs/' \
    --exclude='repro/' \
    --exclude='*.pyc' \
    --exclude='*.pyo' \
    --exclude='*.distcp' \
    --exclude='*.safetensors' \
    --exclude='*.arrow' \
    --exclude='*.npy' \
    --exclude='*.npz' \
    --exclude='*.pt' \
    --exclude='*.pth' \
    --exclude='*.ckpt' \
    --exclude='miniforge.sh' \
    "${SRC_DIR}/" "${DEST_DIR}/"
}

copy_with_tar() {
  (
    cd "${SRC_DIR}"
    tar \
      --exclude='./.git' \
      --exclude='*/.git' \
      --exclude='./.gitmodules' \
      --exclude='./.cache' \
      --exclude='*/.cache' \
      --exclude='./__pycache__' \
      --exclude='*/__pycache__' \
      --exclude='./.pytest_cache' \
      --exclude='*/.pytest_cache' \
      --exclude='./.mypy_cache' \
      --exclude='*/.mypy_cache' \
      --exclude='./artifacts' \
      --exclude='./cache' \
      --exclude='./logs' \
      --exclude='./miniforge' \
      --exclude='./outputs' \
      --exclude='./repro' \
      --exclude='*.pyc' \
      --exclude='*.pyo' \
      --exclude='*.distcp' \
      --exclude='*.safetensors' \
      --exclude='*.arrow' \
      --exclude='*.npy' \
      --exclude='*.npz' \
      --exclude='*.pt' \
      --exclude='*.pth' \
      --exclude='*.ckpt' \
      --exclude='./miniforge.sh' \
      -cf - .
  ) | (
    cd "${DEST_DIR}"
    tar -xf -
  )
}

# Copy a code-first snapshot and skip the multi-GB training artifacts.
if command -v rsync >/dev/null 2>&1; then
  copy_with_rsync
elif command -v tar >/dev/null 2>&1; then
  copy_with_tar
else
  echo "Neither rsync nor tar is available on this system." >&2
  exit 1
fi

cat > "${DEST_DIR}/.gitignore" <<'EOF'
# Generated by export_clean_repo.sh
.cache/
__pycache__/
.pytest_cache/
.mypy_cache/
*.pyc
*.pyo

# Local env / installers
miniforge/
miniforge.sh

# Large training artifacts
artifacts/
cache/
logs/
outputs/
repro/

# Model and dataset shards
*.distcp
*.safetensors
*.arrow
*.npy
*.npz
*.pt
*.pth
*.ckpt
EOF

echo
echo "Clean snapshot created at: ${DEST_DIR}"
echo
echo "Next steps:"
echo "  cd ${DEST_DIR}"
echo "  git init -b main"
echo "  git add ."
echo "  git commit -m 'Initial import of olmo3_sft'"
echo "  git remote add origin <your-repo-url>"
echo "  git push -u origin main"
